name: NodeJS with Webpack Deploy to Aliyun ECS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack

      - name: Deploy to Aliyun ECS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SERVER_SSH_KEY }}
          script: |
            #!/bin/bash

            # 设置脚本执行失败时退出
            set -e

            # 创建存放项目文件的目录
            mkdir -p /home/garyli/git_action_webpack_starter

            # 进入项目目录
            cd /home/garyli/git_action_webpack_starter

            # 定义日志文件路径
            LOG_FILE="/home/garyli/git_action_webpack_starter/deploy_log.txt"

            # 定义记录日志的函数
            log() {
              local timestamp
              timestamp=$(date +"%Y-%m-%d %H:%M:%S")
              echo "[$timestamp] $1" | tee -a "$LOG_FILE"
            }

            # 传输构建文件
            log "Transferring the built files..."            
            rsync -avz --exclude='.git' --exclude='node_modules' --exclude='.github' --exclude='**/node_modules' . .
            log "Files transferred successfully."

            # 重启应用服务
            # log "Restarting the application..."
            # systemctl restart your-application.service
            # log "Application restarted successfully."

            # 记录脚本执行完成的日志
            log "Deploy script completed."

           
         