name: NodeJS with Webpack Deploy to Aliyun ECS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install

    - name: Build project
      run: |
        npx webpack

    - name: Deploy to Aliyun ECS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SERVER_SSH_KEY }}
        script: |
          #!/bin/bash

          # 设置脚本执行失败时退出
          set -e

          # 确保目标目录存在
          mkdir -p /home/garyli/webpack_starter
          cd /home/garyli/webpack_starter

          # 定义日志文件路径
          LOG_FILE="/home/garyli/webpack_starter/deploy_log.txt"

          # 定义记录日志的函数
          log() {
            local timestamp
            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
            echo "[$timestamp] $1" | tee -a "$LOG_FILE"
          }

          # 记录脚本开始执行的日志
          log "Deploy script started."

          # 同步仓库
          log "Transferring the built files..."
          rsync -avz --exclude='.git' --exclude='node_modules' --exclude='.github' --exclude='**/node_modules' . /home/garyli/webpack_starter
          log "Files transferred successfully."

          # 记录脚本执行完成的日志
          log "Deploy script completed."